[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[profile.dev]
debug = true

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "engine-cli"
path = "src/main.rs"

[dependencies]
bitflags = "1.3"
lazy_static = "1.4"
wasm-bindgen = "0.2"